#! /usr/bin/env python

# Preferred abbreviations?
# this should be 1 to 1 I guess... add abbr to BIBLE_ABBR_MAP
BIBLE_ABBRS = { "Genesis": "Gen", "Exodus": "Exo", "Leviticus": "Lev", 
                "Numbers": "Num", "Deuteronomy": "Deu", "Joshua": "Jos",
		"Judges": "Jud", "Ruth": "Rut", "1 Samuel": "1Sam", 
		"2 Samuel": "2Sam", 
                "1 Kings": "1Kg", 
                "2 Kings": "2Kg", 
		"1 Chronicles": "1Chr", 
		"2 Chronicles": "2Chr", "Ezra": "Ezr", "Nehemiah": "Neh", 
		"Esther": "Est", "Job": "Job", "Psalm": "Psa", 
		"Proverbs": "Pro", 
		"Ecclesiastes": "Ecl", 
                "Song of Solomon": "Sos", 
		"Isaiah": "Isa", 
		"Jeremiah": "Jer", "Lamentations": "Lam", "Ezekiel": "Eze", 
		"Daniel": "Dan", "Hosea": "Hos", "Joel": "Joe", 
		"Amos": "Amo", 
		"Obadiah": "Oba", "Jonah": "Jon", "Micah": "Mic", 
		"Nahum": "Nah", 
		"Habakkuk": "Hab", "Zephaniah": "Zep", "Haggai": "Hag", 
		"Zechariah": "Zec", "Malachi": "Mal", "Matthew": "Mt", 
		"Mark": "Mk", "Luke": "Lk", "John": "Jn", "Acts": "Act", 
		"Romans": "Rom", "1 Corinthians": "1Cor", 
		"2 Corinthians": "2Cor", "Galatians": "Gal", 
		"Ephesians": "Eph", "Philippians": "Phi", 
		"Colossians": "Col", 
                "1 Thessalonians": "1Th", 
		"2 Thessalonians": "2Th", 
                "1 Timothy": "1Tim", 
		"2 Timothy": "2Tim", "Titus": "Tit", 
		"Philemon": "Phm", "Hebrews": "Heb", 
		"James": "Jas", "1 Peter": "1Pet", 
		"2 Peter": "2Pet", "1 John": "1Jn", "2 John": "2Jn", 
		"3 John": "3Jn", "Jude": "Jd", "Revelation": "Rev" }

# Roman numerals not accepted ie II Timothy
# letters (eg 1b) not accepted either
BIBLE_ABBR_MAP = { 
                  "gen": "genesis",
                  "exo": "exodus",
                  "ex": "exodus",
                  "lev": "leviticus",
                  "num": "numbers",
                  "deu": "deuteronomy",
                  "jos": "joshua",
                  "josh": "joshua",
                  "jud": "judges",
                  "rut": "ruth",
                  "1sam": "1 samuel",
                  "2sam": "2 samuel",
                  "1kg": "1 kings",
                  "1ki": "1 kings",
                  "1kgs": "1 kings",
                  "2kg": "2 kings",
                  "2ki": "2 kings",
                  "2kgs": "2 kings",
                  "1chr": "1 chronicles",
                  "2chr": "2 chronicles",
                  "1chron": "1 chronicles",
                  "ezr": "ezra",
                  "ez": "ezra",
                  "neh": "nehemiah",
                  "est": "esther",
                  "es": "esther",
                  "psa": "psalm",
                  "ps": "psalm",
                  "pro": "proverbs" ,
                  "prov": "proverbs" ,
                  "pr": "proverbs" ,
                  "ecc": "ecclesiastes",
                  "ecl": "ecclesiastes",
                  "eccl": "ecclesiastes",
                  "sos": "song of solomon",
                  "isa": "isaiah",
                  "is": "isaiah",
                  "jer": "jeremiah",
                  "lam": "lamentations",
                  "eze": "ezekiel",
                  "dan": "daniel",
                  "hos": "hosea",
                  "joe": "joel",
                  "amo": "amos" ,
                  "oba": "obadiah",
                  "jon": "jonah",
                  "mic": "micah",
                  "nah": "nahum",
                  "hab": "habakkuk",
                  "zep": "zephaniah",
                  "hag": "haggai",
                  "zec": "zechariah",
                  "mal": "malachi",
                  "mt": "matthew",
                  "matt": "matthew",
                  "mk": "mark",
                  "mk": "mark",
                  "lk": "luke",
                  "jn": "john",
                  "act": "acts",
                  "rom": "romans",
                  "rm": "romans",
                  "1cor": "1 corinthians",
                  "2cor": "2 corinthians",
                  "gal": "galatians",
                  "eph": "ephesians",
                  "phi": "philippians",
                  "phil": "philippians",
                  "col": "colossians",
                  "1th": "1 thessalonians",
                  "1ths": "1 thessalonians",
                  "1thes": "1 thessalonians",
                  "2th": "2 thessalonians",
                  "2ths": "2 thessalonians",
                  "2thes": "2 thessalonians",
                  "1tim": "1 timothy",
                  "2tim": "2 timothy",
                  "tit": "titus",
                  "phm": "philemon",
                  "heb": "hebrews",
                  "jas": "james",
                  "1pet": "1 peter",
                  "2pet": "2 peter",
                  "1jn": "1 john",
                  "2jn": "2 john",
                  "3jn": "3 john",
                  "jd": "jude",
                  "rev": "revelation",
                  "rv": "revelation" 
                 }

